server {
    listen 443 ssl http2;
    server_name example.lab.local;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /etc/ssl/example/fullchain.pem;
    ssl_certificate_key /etc/ssl/example/privkey.pem;

    ssl_prefer_server_ciphers off;

    location / {
        return 200 "Lab 4 TLS deployment demo\n";
    }
}

